# Generated by Django 5.1.9 on 2025-05-25 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Main Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PostStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('blocked', 'Blocked'), ('canceled', 'Canceled'), ('suspended', 'Suspended')], max_length=20, unique=True, verbose_name='Status Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Post Status',
                'verbose_name_plural': 'Post Statuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RealEstateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='real_estate/%Y/%m/%d/', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
            ],
            options={
                'verbose_name': 'Real Estate Image',
                'verbose_name_plural': 'Real Estate Images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_purpose', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=10, verbose_name='Listing Purpose')),
                ('property_type', models.CharField(choices=[('houses', 'Houses'), ('apartments', 'Apartments'), ('rooms', 'Rooms'), ('commercial', 'Commercial'), ('other', 'Other')], max_length=20, verbose_name='Property Type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost')),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bedrooms')),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Bathrooms')),
                ('square_feet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Square Feet')),
                ('year_built', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year Built')),
                ('parking', models.CharField(choices=[('none', 'None'), ('street', 'Street'), ('garage', 'Garage'), ('lot', 'Lot')], default='none', max_length=10, verbose_name='Parking')),
                ('heating', models.CharField(choices=[('none', 'None'), ('central', 'Central'), ('electric', 'Electric'), ('gas', 'Gas'), ('other', 'Other')], default='none', max_length=10, verbose_name='Heating')),
                ('cooling', models.CharField(choices=[('none', 'None'), ('central', 'Central'), ('window', 'Window'), ('other', 'Other')], default='none', max_length=10, verbose_name='Cooling')),
                ('zip_code', models.CharField(max_length=5, verbose_name='Zip Code')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('hide_address', models.BooleanField(default=False, verbose_name='Hide Address')),
                ('availability_date', models.DateField(blank=True, null=True, verbose_name='Availability Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estates', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ads.poststatus', verbose_name='Status')),
                ('images', models.ManyToManyField(blank=True, to='ads.realestateimage', verbose_name='Images')),
            ],
            options={
                'verbose_name': 'Real Estate',
                'verbose_name_plural': 'Real Estates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ads.maincategory')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
                'ordering': ['main_category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.maincategory')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ads.poststatus', verbose_name='Status')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.subcategory')),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
                'ordering': ['-created_at'],
            },
        ),
    ]
