# Generated by Django 5.1.9 on 2025-05-25 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, verbose_name='Icon')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubcategories', to='ads.maincategory')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubcategories', to='ads.subcategory')),
            ],
            options={
                'verbose_name': 'Sub Sub Category',
                'verbose_name_plural': 'Sub Sub Categories',
                'ordering': ['main_category', 'sub_category', 'name'],
                'unique_together': {('main_category', 'sub_category', 'name')},
            },
        ),
    ]
