# Generated by Django 5.1.9 on 2025-05-26 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_add_post_statuses'),
        ('ads', '0003_alter_ad_author_alter_ad_created_at_and_more'),
    ]

    operations = [
    ]
