# Generated by Django 5.1.9 on 2025-05-27 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_remove_draftad_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestate',
            name='lease_term',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lease Term'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estates', to='ads.maincategory'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estates', to='ads.subcategory'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Listing Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestate',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
    ]
