# Generated by Django 5.2.1 on 2025-05-17 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_user_phone_verified_user_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1 (XXX) XXX-XXXX'", regex='^\\+1 \\(\\d{3}\\) \\d{3}-\\d{4}$')], verbose_name='Phone'),
        ),
    ]
