# Generated by Django 5.1.9 on 2025-05-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_age_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('suspended', 'Suspended')], default='active', max_length=20, verbose_name='User Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('personal', 'Personal'), ('personal_pro', 'Personal Pro'), ('business', 'Business'), ('business_pro', 'Business Pro')], default='personal', max_length=20, verbose_name='User Type'),
        ),
    ]
